name: Django CI/CD Workflow

on:
  pull_request:
    branches:
      - master
      - develop
    push:
      branches:
        - master
        - develop

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check python version
        run: python -m pip --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Syntax
        run: pycodestyle --statistics .
      - name: Run Migration
        run: python manage.py migrate
      - name: Run Tests
        run: python manage.py test

    package-job:
      runs-on: ubuntu-latest
      needs: [health-check-job]
      if: ${{ github.event_name == 'push' }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Build & Publish Image
          uses: docker/build-push-action@v2
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}

